# Generated by Django 4.1.5 on 2023-01-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_url', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('http_referer', models.CharField(max_length=50)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
