# Generated by Django 4.1.5 on 2023-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_url', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
